steps:

# GitHubからリポジトリをクローン
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/sayu349/cloud-build-test']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']